"""
Utilities for parsing JSON returned by LLMs.

Provides helper methods to clean and safely parse JSON-like
responses generated by large language models (LLMs).
Handles common formatting issues such as code fences and
extra whitespace before attempting to load JSON.
"""

import json


class JsonParser:
    """
    Cleans and parses LLM JSON responses.

    Responsibilities:
        - Strip unwanted code fences (```json, ```).
        - Remove leading/trailing whitespace.
        - Convert cleaned content into a Python dictionary.

    Methods:
        loads(content: str) -> dict:
            Clean and parse JSON string into a Python dictionary.
    """

    @staticmethod
    def loads(content: str) -> dict:
        """
        Convert LLM output into a Python dictionary.

        Args:
            content (str): Raw JSON-like string returned by an LLM.

        Returns:
            dict: Parsed Python dictionary.

        Raises:
            json.JSONDecodeError: If the cleaned content is not valid JSON.
        """
        content = content.strip()

        # Remove common LLM code fences
        if content.startswith("```json"):
            content = content.removeprefix("```json")

        if content.startswith("```"):
            content = content.removeprefix("```")

        if content.endswith("```"):
            content = content.removesuffix("```")

        content = content.strip()

        # Parse into dictionary
        return json.loads(content)
