"""
Base interface for all AI providers.

Defines the abstract base class that all AI provider implementations
must inherit from. This ensures a consistent contract for generating
text, structured JSON, and performing health checks across providers.
"""

from abc import ABC, abstractmethod

from ai_resume_analyzer.schemas.ai import AIResponse


class AIProvider(ABC):
    """
    Abstract base class for all AI providers.

    Responsibilities:
        - Define a common interface for AI provider implementations.
        - Enforce consistent method signatures across providers.
        - Support multiple output formats (text, JSON).
        - Provide health checks to verify provider availability.

    Methods:
        generate_text(prompt: str, context: str) -> AIResponse:
            Generate a text response based on the given prompt and context.

        generate_json(prompt: str, context: str) -> dict:
            Generate a structured JSON response based on the given prompt and context.

        health_check() -> bool:
            Verify provider availability and readiness.
    """

    @abstractmethod
    def generate_text(self, prompt: str, context: str) -> AIResponse:
        """
        Generate a text response.

        Args:
            prompt (str): The input prompt for the AI provider.
            context (str): Additional context to guide the response.

        Returns:
            AIResponse: A structured response object containing generated text.
        """
        pass

    @abstractmethod
    def generate_json(self, prompt: str, context: str) -> dict:
        """
        Generate a JSON response.

        Args:
            prompt (str): The input prompt for the AI provider.
            context (str): Additional context to guide the response.

        Returns:
            dict: A structured JSON object generated by the provider.
        """
        pass

    @abstractmethod
    def health_check(self) -> bool:
        """
        Verify provider availability.

        Returns:
            bool: True if the provider is available, False otherwise.
        """
        pass
